// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKnR_Afz_0Qwiyf6tgc3YncgHAnbw-Big',
    appId: '1:479036331642:web:97df33064435ae49bc0dc3',
    messagingSenderId: '479036331642',
    projectId: 'noize-firebase',
    authDomain: 'noize-firebase.firebaseapp.com',
    databaseURL: 'https://noize-firebase-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'noize-firebase.appspot.com',
    measurementId: 'G-ERV0MMGEP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG8LCRcpYAIg3To_x5ziI4wqE4U18B97s',
    appId: '1:479036331642:android:1120d5dff811a886bc0dc3',
    messagingSenderId: '479036331642',
    projectId: 'noize-firebase',
    databaseURL: 'https://noize-firebase-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'noize-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8gm5Gi6ECwLaLZOsg5PL4kqxQWfRS1yo',
    appId: '1:479036331642:ios:ce1c5c95ccb0d301bc0dc3',
    messagingSenderId: '479036331642',
    projectId: 'noize-firebase',
    databaseURL: 'https://noize-firebase-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'noize-firebase.appspot.com',
    iosClientId: '479036331642-t13p4kgc3feus3ema2for9bls7s55rov.apps.googleusercontent.com',
    iosBundleId: 'com.example.geolocator',
  );
}
